# Generated by Django 2.1.1 on 2019-05-28 14:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrintedModelQuality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality_number', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('thumbnail', models.ImageField(default='Images/Group_21.png', upload_to='Images/')),
                ('build_volume', models.TextField()),
                ('printer_type', models.CharField(choices=[('CR', 'Cartesian'), ('DL', 'Delta')], default='CR', max_length=2)),
                ('ip_address', models.GenericIPAddressField(default='0.0.0.0')),
                ('port_number', models.IntegerField(default=5000)),
                ('is_printing', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PrintingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('name', models.TextField()),
                ('thing_dimensions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('printer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='printerIO.Printer')),
                ('printing_models', models.ManyToManyField(to='printerIO.PrintingModel')),
            ],
        ),
        migrations.AddField(
            model_name='printedmodelquality',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_model', to='printerIO.PrintingModel'),
        ),
        migrations.AddField(
            model_name='printedmodelquality',
            name='printer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_printer', to='printerIO.Printer'),
        ),
    ]
