# Generated by Django 2.1.5 on 2019-05-01 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='Images/')),
                ('build_volume', models.TextField()),
                ('printer_type', models.CharField(choices=[('CR', 'Cartesian'), ('DL', 'Delta')], default='CR', max_length=2)),
                ('is_printing', models.BooleanField(default=False)),
            ],
        ),
    ]
