# Generated by Django 2.1.1 on 2019-05-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printerIO', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='password',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='printer',
            name='username',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
