# Generated by Django 2.1.5 on 2019-05-01 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printerIO', '0002_auto_20190501_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('name', models.TextField()),
                ('thing_dimensions', models.TextField()),
            ],
        ),
    ]
