# Generated by Django 2.1.5 on 2019-05-01 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printerIO', '0003_printingmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('printer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='printerIO.Printer')),
                ('objects', models.ManyToManyField(to='printerIO.PrintingModel')),
            ],
        ),
    ]
