# Generated by Django 2.1.1 on 2019-06-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printerIO', '0003_auto_20190602_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
    ]
