# Generated by Django 2.1.1 on 2019-06-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printerIO', '0005_printedmodelquality_was_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='has_heated_chamber',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='printer',
            name='number_of_extruders',
            field=models.IntegerField(default=1),
        ),
    ]
