# Generated by Django 2.1.1 on 2019-05-15 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printerIO', '0005_auto_20190515_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queue',
            old_name='objects_to_print',
            new_name='printing_models',
        ),
    ]
