# Generated by Django 2.1.1 on 2019-05-17 19:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printerIO', '0006_auto_20190515_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintedModelQuality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality_number', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printerIO.PrintingModel')),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printerIO.Printer')),
            ],
        ),
    ]
