# Generated by Django 2.1.1 on 2019-06-19 11:19

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('printerIO', '0006_auto_20190609_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('diameter', models.FloatField(choices=[(1.75, '1.75mm diameter'), (3, '3mm diameter')], default=1.75, max_length=5)),
                ('weight', models.FloatField(default=1)),
                ('filament_left', models.FloatField(default=1)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField(blank=True)),
                ('created', models.DateField(default=datetime.datetime(2019, 6, 19, 11, 19, 55, 188590, tzinfo=utc))),
                ('due', models.DateField(blank=True, default=datetime.datetime(2019, 6, 19, 11, 19, 55, 221987, tzinfo=utc))),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printerIO.TaskCategory'),
        ),
    ]
