# Generated by Django 2.1.1 on 2019-06-19 11:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('printerIO', '0007_auto_20190619_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='task',
            name='due',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
