# Generated by Django 2.1.1 on 2019-06-19 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printerIO', '0008_auto_20190619_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printerIO.TaskCategory'),
        ),
    ]
