# Generated by Django 2.1.1 on 2019-06-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printerIO', '0009_auto_20190619_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='filament',
            name='filament_type',
            field=models.CharField(default='PLA', max_length=250),
        ),
        migrations.AddField(
            model_name='printer',
            name='filament',
            field=models.ManyToManyField(blank=True, to='printerIO.Filament'),
        ),
    ]
