# Generated by Django 2.1.1 on 2019-06-24 19:34

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('printerIO', '0010_auto_20190619_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.IntegerField(validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)])),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('timestamp', models.DateField(default=django.utils.timezone.now)),
                ('state', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='filament',
            name='colour',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='filament',
            name='producer',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='filament',
            name='name',
            field=models.CharField(default='', max_length=250),
        ),
    ]
