exclude: migrations
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: trailing-whitespace
        files: .py$
      - id: flake8
        args: [--max-line-length=88]
        files: .py$
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        files: .py$
  - repo: https://github.com/humitos/mirrors-autoflake/
    rev: v1.3
    hooks:
      - id: autoflake
        args:
          [
            "--in-place",
            "--remove-all-unused-imports",
            "--remove-unused-variable",
          ]
  - repo: https://github.com/prettier/prettier
    rev: "" # Use the sha or tag you want to point at
    hooks:
      - id: prettier
        exclude: .html$
